# Generated by Django 4.0.2 on 2022-02-06 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=60, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=60, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('editor', models.BooleanField(default=False)),
                ('github', models.URLField(blank=True, max_length=128, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=128, null=True)),
                ('email', models.URLField(blank=True, max_length=128, null=True)),
                ('portfolio', models.URLField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Profile's",
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('thumbnail', models.ImageField(upload_to='Project Thumbnails')),
                ('Description', models.TextField(blank=True, max_length=150, null=True)),
                ('github', models.URLField(blank=True, max_length=128, null=True)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('contributors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
