# Generated by Django 4.0.2 on 2022-02-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Talent', 'Talent'), ('Recruiter', 'Recruiter')], max_length=20, null=True),
        ),
    ]
