# Generated by Django 4.0.2 on 2022-02-06 06:49

import builtins
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(verbose_name=builtins.max)),
            ],
            options={
                'verbose_name_plural': "Categorie's",
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Thumbnail', models.ImageField(blank=True, null=True, upload_to='Blog Thumbnails')),
                ('overview', models.TextField(max_length=150)),
                ('body_text', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('publish', models.BooleanField(default=False)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Blog's",
            },
        ),
    ]
