# Generated by Django 4.0.2 on 2022-02-06 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('activity', '0003_projectlike_project_alter_projectlike_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlike',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project'),
        ),
    ]
