# Generated by Django 4.0.2 on 2022-02-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_blog_options_alter_category_options'),
        ('activity', '0005_alter_projectlike_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcomment',
            options={'verbose_name_plural': 'Project Comments'},
        ),
        migrations.AlterModelOptions(
            name='projectlike',
            options={'verbose_name_plural': 'Project Likes'},
        ),
        migrations.AlterModelOptions(
            name='projectreply',
            options={'verbose_name_plural': 'Project Replies'},
        ),
        migrations.CreateModel(
            name='BlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog Likes',
            },
        ),
    ]
