# Generated by Django 4.0.2 on 2022-02-06 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_company_options_alter_experience_options_and_more'),
        ('activity', '0007_blogcomment_blogreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=80)),
                ('redirect_to', models.URLField(blank=True, max_length=128, null=True)),
                ('seen', models.BooleanField(default=True)),
                ('notification_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('notification_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
