# Generated by Django 4.0.2 on 2022-02-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
