# Generated by Django 4.0.2 on 2022-02-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skill_profile_job_type_profile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=20, null=True),
        ),
    ]
