# Generated by Django 4.0.2 on 2022-02-06 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_profile_level_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followers',
            options={'verbose_name_plural': "Follower's"},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': "Project's"},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': "Skill's"},
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='Company Logos')),
                ('location', models.CharField(max_length=60)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Companie's",
            },
        ),
    ]
